stages:
  load_data:
    cmd: python src/stage_1_load_save.py --config=config/config.yaml
    deps:
      - src/stage_1_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts_1/raw_local_dir/data.csv
  split_data:
    cmd: python src/stage_2_split_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_2_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts_1/split_data_dir/train.csv
      - artifacts_1/split_data_dir/test.csv